### ISSUE TITLE
Predicting Labels for Unlabeled Query Images Post-Gallery Creation

### ISSUE THREAD

**Issue by durianc** [bar371/GEFF#13]
Hello @bar371  ! Thank you for the hardwork and sharing of your code. 

**My question is regarding of the project code:**
Is it possible for the project code to **predict labels for unlabeled query images** after the gallery has been created? 
In my understanding, once the gallery is set up with labeled images, I would like to know if the system can infer and suggest labels for new, unlabeled query images based on the gallery's dataset.

I am looking forward to your guidance on this matter. Thank you for your valuable contributions to the field and for considering my question.

**Comment by darkushin** [comment]
Hi @durianc,
Thank you for your interest in our project.

Generally speaking, the task of ReID is to predict an identity for **unlabeled** query samples. The reason the query is usually labeled in ReID datasets is to allow easy evaluation of the model. However, the model doesn't need the ground-truth labels of the query to make a prediction.

Once you have a labeled gallery, the process of predicting the label for an unlabeled query would be as follows:
1. Extract a feature vector for the query using the ReID model.
2. Extract feature vectors for all the gallery samples using the ReID model.
3. Compute the distance vector for the query sample and all gallery samples, i.e. the i'th entrance in the vector represents the distance between the query feature vector and the feature vector of the i'th sample in the gallery,
4. Define the identity of the query sample according to the most similar gallery sample (the sample with the lowest distance in the distance vector). Alternatively, you can think of other methods to choose the best match, e.g. majority vote of the k most similar gallery samples, etc.

You can refer to the [reid_inference](https://github.com/bar371/GEFF/blob/421384c0199b658825fd4ad0a31e7d920461c093/Scripts/inference.py#L243) function to see an example how we extract the feature vectors and compute the distance matrix.

**Comment by durianc** [comment]
Thank you for your reply!
