### ISSUE TITLE
The runtime for using the CCVID dataset in gallery_enrichment.py is excessively long.

### ISSUE THREAD

**Issue by xz-zhou** [bar371/GEFF#4]
Hello, could you please tell me how long it took you to run gallery_enrichment.py on CCIVD? I've been running it on a cloud server with a 16GB DPU for almost two days, and the code is still not finished. Is this situation normal?

**Comment by bar371** [comment]
Dear @zhouxinzhu-maker, thank you for your interest in our work.

Please try and run the gallery_enrichment.py script in Google Colab per our instructions in the Readme. For us the enrichment process takes around 2.5 hours.

**Comment by xz-zhou** [comment]
I appreciate your response to my question amidst your busy schedule. I've switched to a different CPU, which allowed me to run the code in approximately 24 hours.
